version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: beebop
            MYSQL_DATABASE: beebop
            MYSQL_USER: beebop
            MYSQL_PASSWORD: 4ZNepTxSWpSbStju
        volumes:
            - mysql-data:/var/lib/mysql
    php:
        build: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ./symfony:/var/www/symfony
            - symfony-logs:/var/www/symfony/app/logs
            - ./php-fpm/beebop_start.sh:/usr/local/bin/beebop_start
        links:
            - db
        depends_on:
            - db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - nginx-logs:/var/log/nginx


volumes:
  mysql-data:
    driver: local
  symfony-logs:
    driver: local
  nginx-logs:
    driver: local